
name: O Filosofia

on:
  schedule:
    - cron: "0 11 * * *"  # 8h Brasil
  workflow_dispatch:

jobs:
  postar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
        run: python bot_mastodon_filosofia.py
